"""Parsing the resolved plant document into the model.

Two stages, deliberately. `schema()` is a voluptuous schema that rejects
anything malformed — including **unknown keys**, so a typo is an error rather
than a silently ignored field. `parse()` then builds the frozen model objects,
where the dataclasses' own `__post_init__` checks catch anything a shape check
cannot (a field capacity below the dry point, a zero interval).

The strictness is the point. This document is machine-generated by a tool that
already validated it, so anything surprising here means the two have diverged —
and failing loudly at startup is far better than a dashboard of `unavailable`
entities nobody notices for a week.

Uses plain voluptuous rather than `homeassistant.helpers.config_validation`, so
this module stays importable without Home Assistant and its tests need no mocks.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

import voluptuous as vol

from .plant import (
    Calibrated,
    Calibrating,
    Calibration,
    CareTask,
    Moisture,
    Plant,
    ProbeFacts,
    SourceEntity,
)

# Field names, named once. A typo in a key then breaks the schema rather than
# quietly reading a field that is always absent.
FIELD_PLANTS = "plants"
FIELD_NAME = "name"
FIELD_DISPLAY = "display"
FIELD_SPECIES = "species"
FIELD_MOISTURE = "moisture"
FIELD_SOURCE = "source"
FIELD_ENTITIES = "entities"
FIELD_PROBE = "probe"
FIELD_CALIBRATION = "calibration"
FIELD_CARE = "care"

FIELD_ENTITY_MOISTURE = "moisture"
FIELD_ENTITY_TEMPERATURE = "temperature"
FIELD_ENTITY_BATTERY = "battery"

FIELD_HEARTBEAT_MINUTES = "heartbeatMinutes"
FIELD_DEADBAND_PP = "deadbandPp"

FIELD_FIELD_CAPACITY = "fieldCapacity"
FIELD_DRY_POINT = "dryPoint"
FIELD_FC_TOLERANCE = "fcTolerance"

FIELD_TASK = "task"
FIELD_ICON = "icon"
FIELD_EVERY_DAYS = "everyDays"


class InvalidPlantConfig(Exception):
    """Raised when the resolved document cannot be turned into a model.

    Carries the plant name wherever one is known: these messages reach a human
    reading Home Assistant's log, and "missing field" without saying which plant
    is most of the way to useless in a file with a dozen in it.
    """


def _entity_id(value: Any) -> str:
    if not isinstance(value, str) or "." not in value:
        raise vol.Invalid(f"expected an entity id like 'sensor.foo', got {value!r}")
    return value


def _entities_schema() -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(FIELD_ENTITY_MOISTURE): _entity_id,
            vol.Optional(FIELD_ENTITY_TEMPERATURE): _entity_id,
            vol.Optional(FIELD_ENTITY_BATTERY): _entity_id,
        }
    )


def _probe_schema() -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(FIELD_HEARTBEAT_MINUTES): vol.All(int, vol.Range(min=1)),
            vol.Required(FIELD_DEADBAND_PP): vol.All(
                vol.Coerce(float), vol.Range(min=0)
            ),
        }
    )


def _calibration_schema() -> vol.Schema:
    # Both endpoints required together: a calibration with only one is the
    # precise thing the input format exists to refuse, because a threshold
    # derived from one endpoint is a fabricated number.
    return vol.Schema(
        {
            vol.Required(FIELD_FIELD_CAPACITY): vol.Coerce(float),
            vol.Required(FIELD_DRY_POINT): vol.Coerce(float),
            vol.Optional(FIELD_FC_TOLERANCE): vol.Coerce(float),
        }
    )


def _moisture_schema() -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(FIELD_SOURCE): str,
            vol.Required(FIELD_ENTITIES): _entities_schema(),
            vol.Required(FIELD_PROBE): _probe_schema(),
            # Absent means calibrating. See `parse_calibration`.
            vol.Optional(FIELD_CALIBRATION): _calibration_schema(),
        }
    )


def _care_schema() -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(FIELD_TASK): str,
            vol.Required(FIELD_DISPLAY): str,
            vol.Required(FIELD_ICON): str,
            vol.Required(FIELD_EVERY_DAYS): vol.All(int, vol.Range(min=1)),
        }
    )


def _plant_schema() -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(FIELD_NAME): str,
            vol.Required(FIELD_DISPLAY): str,
            vol.Optional(FIELD_SPECIES): str,
            vol.Optional(FIELD_MOISTURE): _moisture_schema(),
            vol.Optional(FIELD_CARE): [_care_schema()],
        }
    )


def schema() -> vol.Schema:
    """The whole `plant_care:` block.

    `PREVENT_EXTRA` is the default for a `vol.Schema`, so an unexpected key
    anywhere in this tree is an error. That is deliberate: the document is
    generated, so an unknown key means the generator emitted something this
    version does not understand, and running on a partial understanding of the
    config is worse than not starting.
    """
    return vol.Schema({vol.Required(FIELD_PLANTS): [_plant_schema()]})


def parse_calibration(data: Mapping[str, Any] | None, plant_name: str) -> Calibration:
    """Absence means calibrating — never a default.

    This is the one contract the generator and this component must agree on. A
    default substituted here would invent exactly the number the input format
    refuses to let anyone invent, and the plant would be judged against it
    without anybody choosing it.
    """
    if data is None:
        return Calibrating()
    try:
        return Calibrated(
            field_capacity=data[FIELD_FIELD_CAPACITY],
            dry_point=data[FIELD_DRY_POINT],
            fc_tolerance=data.get(FIELD_FC_TOLERANCE),
        )
    except ValueError as err:
        raise InvalidPlantConfig(f"plant '{plant_name}': {err}") from err


def _parse_moisture(data: Mapping[str, Any], plant_name: str) -> Moisture:
    entities = data[FIELD_ENTITIES]
    temperature = entities.get(FIELD_ENTITY_TEMPERATURE)
    battery = entities.get(FIELD_ENTITY_BATTERY)

    try:
        probe = ProbeFacts(
            heartbeat_minutes=data[FIELD_PROBE][FIELD_HEARTBEAT_MINUTES],
            deadband_pp=data[FIELD_PROBE][FIELD_DEADBAND_PP],
        )
    except ValueError as err:
        raise InvalidPlantConfig(f"plant '{plant_name}': {err}") from err

    return Moisture(
        source=data[FIELD_SOURCE],
        moisture_entity=SourceEntity(entities[FIELD_ENTITY_MOISTURE]),
        temperature_entity=SourceEntity(temperature) if temperature else None,
        battery_entity=SourceEntity(battery) if battery else None,
        probe=probe,
        calibration=parse_calibration(data.get(FIELD_CALIBRATION), plant_name),
    )


def _parse_plant(data: Mapping[str, Any]) -> Plant:
    name = data[FIELD_NAME]
    moisture_data = data.get(FIELD_MOISTURE)

    care: list[CareTask] = []
    for entry in data.get(FIELD_CARE, []):
        try:
            care.append(
                CareTask(
                    task=entry[FIELD_TASK],
                    display=entry[FIELD_DISPLAY],
                    icon=entry[FIELD_ICON],
                    every_days=entry[FIELD_EVERY_DAYS],
                )
            )
        except ValueError as err:
            raise InvalidPlantConfig(f"plant '{name}': {err}") from err

    return Plant(
        name=name,
        display=data[FIELD_DISPLAY],
        species=data.get(FIELD_SPECIES),
        moisture=_parse_moisture(moisture_data, name) if moisture_data else None,
        care=tuple(care),
    )


def parse(data: Mapping[str, Any]) -> tuple[Plant, ...]:
    """Build the model from an already schema-validated document.

    Duplicate names are rejected here rather than by the schema: every entity id
    this component creates is built from the plant name, so two plants sharing
    one would collide silently and the second would win.
    """
    plants = tuple(_parse_plant(entry) for entry in data[FIELD_PLANTS])

    seen: set[str] = set()
    for plant in plants:
        if plant.name in seen:
            raise InvalidPlantConfig(f"plant '{plant.name}' is defined more than once")
        seen.add(plant.name)

    return plants
