"""Plant care: moisture monitoring, care tasks, and one outstanding feed.

Configured from a file rather than a config flow, so the configuration lives in
git. The file is generated by homelab-data, which validates plants against a
zigbee device inventory that neither Home Assistant nor zigbee2mqtt can see on
its own; by the time it reaches here every device reference has already been
resolved to an entity id.

    plant_care: !include dynamic/plants.yaml

**This module imports no Home Assistant at runtime.** Importing
`custom_components.plant_care.model` runs this file first, so an unguarded HA
import here would drag the framework into every unit test and force them to mock
it. The framework imports are therefore either `TYPE_CHECKING`-only (so the type
hints stay real) or done inside `async_setup`, which never runs outside Home
Assistant. `tests/test_no_ha_imports.py` enforces it.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

import voluptuous as vol

from .const import DOMAIN
from .model import DEFAULT_POLICY, Plant, Policy, parse, schema
from .store import STORAGE_KEY, STORAGE_VERSION, CareLog

if TYPE_CHECKING:
    from homeassistant.core import HomeAssistant
    from homeassistant.helpers.typing import ConfigType

_LOGGER = logging.getLogger(__name__)

# Plain strings rather than `homeassistant.const.Platform`, which would be a
# runtime HA import for three values that are stable identifiers anyway.
PLATFORMS: tuple[str, ...] = ("sensor", "binary_sensor", "button")

# The schema is strict — unknown keys are rejected. The document is generated,
# so an unexpected key means the generator emitted something this version does
# not understand, and running on a partial understanding of the config is worse
# than refusing to start.
CONFIG_SCHEMA = vol.Schema({DOMAIN: schema()}, extra=vol.ALLOW_EXTRA)


@dataclass(frozen=True)
class PlantCareData:
    """What the platforms need, assembled once at setup.

    Held in `hass.data[DOMAIN]` rather than passed through discovery info,
    because discovery info has to be JSON-serialisable and these are real typed
    objects — which is the entire point of having parsed them.
    """

    plants: tuple[Plant, ...]
    policy: Policy
    care_log: CareLog


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    # Imported here rather than at module scope: see the module docstring.
    from homeassistant.helpers import discovery
    from homeassistant.helpers.storage import Store

    from .dashboards import PlantsDashboard

    domain_config: Mapping[str, Any] | None = config.get(DOMAIN)
    if domain_config is None:
        return True

    # Anything raised here is fatal on purpose. A plant care system that comes
    # up with half its plants missing looks like it is working, and the failure
    # shows up as a plant nobody watered.
    plants = parse(domain_config)

    care_log = CareLog(Store(hass, STORAGE_VERSION, STORAGE_KEY))
    await care_log.async_load()

    hass.data[DOMAIN] = PlantCareData(
        plants=plants,
        policy=DEFAULT_POLICY,
        care_log=care_log,
    )

    _LOGGER.debug(
        "plant_care: loaded %d plants (%d with a moisture probe)",
        len(plants),
        sum(1 for plant in plants if plant.moisture is not None),
    )

    for platform in PLATFORMS:
        hass.async_create_task(
            discovery.async_load_platform(hass, platform, DOMAIN, {}, config)
        )

    PlantsDashboard(plants).add_to_hass(hass)

    return True
